name: video_crud
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.0
  bloc:
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  camera: ^0.10.0+3
  flutter_image_compress: ^1.1.3
  video_thumbnail: ^0.5.3
  video_player: ^2.7.0
  badges: ^3.1.1
  image_picker: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.3.3
  hive_generator: ^2.0.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
